name: GHA

on:
  workflow_call:
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}|${{ github.ref_name }}-renderer
  cancel-in-progress: true


jobs:
  warning_check:
    name: Tests
    runs-on: 'ubuntu-24.04'
    timeout-minutes: 10 # The overall timeout
    permissions:
      actions: write
      checks: write
      contents: write
      pull-requests: write
      statuses: write

    steps:
      # checkout your repository
      - uses: actions/checkout@v5
        with:
          lfs: true
      # run tests by using the gdUnit4-action with Godot version 4.2.1 and the latest GdUnit4 release 
      - uses: MikeSchulze/gdUnit4-action@v1.2.2
        with:
          godot-version: '4.5'
          paths: |
            res://testing/rendering
          timeout: 5
          publish-report: false
          report-name: rendering-gdunit4
